[package]
name = "archivemount-rs"
version = "0.1.0"
authors = ["Franco Bugnano <franco@bugnano.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polyfuse = "*"
anyhow = "*"
libc = "*"
clap = "*"
termios = "*"
relative-path = "*"

